// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 922 07/20/2023)
// Created on Mon Jun 10 10:43:26 2024

adc_manger adc_manger_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.scl(scl_sig) ,	// inout  scl_sig
	.sda(sda_sig) ,	// inout  sda_sig
	.ADC0_Voltage_A(ADC0_Voltage_A_sig) ,	// output [31:0] ADC0_Voltage_A_sig
	.ADC0_Voltage_B(ADC0_Voltage_B_sig) ,	// output [31:0] ADC0_Voltage_B_sig
	.ADC0_Voltage_C(ADC0_Voltage_C_sig) ,	// output [31:0] ADC0_Voltage_C_sig
	.ADC0_Voltage_D(ADC0_Voltage_D_sig) ,	// output [31:0] ADC0_Voltage_D_sig
	.ADC1_Voltage_A(ADC1_Voltage_A_sig) ,	// output [31:0] ADC1_Voltage_A_sig
	.ADC1_Voltage_B(ADC1_Voltage_B_sig) ,	// output [31:0] ADC1_Voltage_B_sig
	.ADC1_Voltage_C(ADC1_Voltage_C_sig) ,	// output [31:0] ADC1_Voltage_C_sig
	.ADC1_Voltage_D(ADC1_Voltage_D_sig) 	// output [31:0] ADC1_Voltage_D_sig
);

defparam adc_manger_inst.DEV_ID = 'b0010000;
