// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 922 07/20/2023)
// Created on Thu Apr 25 13:32:54 2024

BISS_Master BISS_Master_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.POS(POS_sig) ,	// output [25:0] POS_sig
	.ERR(ERR_sig) ,	// output  ERR_sig
	.WARN(WARN_sig) ,	// output  WARN_sig
	.CRC(CRC_sig) ,	// output [5:0] CRC_sig
	.RDY(RDY_sig) ,	// output  RDY_sig
	.BUSY(BUSY_sig) ,	// output  BUSY_sig
	.MCLK(MCLK_sig) ,	// output  MCLK_sig
	.SLO(SLO_sig) 	// input  SLO_sig
);

defparam BISS_Master_inst.input_clk = 100000000;
defparam BISS_Master_inst.bus_clk = 1000000;
