// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 922 07/20/2023)
// Created on Sun Jun  9 18:11:31 2024

i2c_top i2c_top_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.scl(scl_sig) ,	// inout  scl_sig
	.sda(sda_sig) ,	// inout  sda_sig
	.AIN0(AIN0_sig) ,	// output [15:0] AIN0_sig
	.AIN1(AIN1_sig) ,	// output [15:0] AIN1_sig
	.AIN2(AIN2_sig) ,	// output [15:0] AIN2_sig
	.AIN3(AIN3_sig) ,	// output [15:0] AIN3_sig
	.AIN4(AIN4_sig) ,	// output [15:0] AIN4_sig
	.AIN5(AIN5_sig) ,	// output [15:0] AIN5_sig
	.AIN6(AIN6_sig) ,	// output [15:0] AIN6_sig
	.AIN7(AIN7_sig) 	// output [15:0] AIN7_sig
);

defparam i2c_top_inst.DEV_ID = 'b0010000;
